export type AuthorityClass = 'GREEN'|'YELLOW'|'RED';
export type GoalState = 'NEW'|'MODELING'|'PLANNING'|'EXECUTING'|'WAITING_EXTERNAL'|'WAITING_OWNER'|'BLOCKED'|'VERIFYING'|'REPLANNING'|'COMPLETED'|'CANCELLED'|'FAILED';
